version: "3"

services:
  transmitter:
    container_name: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: agent-image
    volumes:
      - ./agent:/root/workspace
    tty: true
    networks:
      - my_network
    ports:
      - "12300:12300"
    depends_on:
      - receiver

  receiver:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-image
    volumes:
      - ./client:/root/workspace
      #- /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    networks:
      - my_network
    ports:
      - "12301:12301" # metric
      - "12302:12302" # video
      - "12303:12303" # config
      - "3000:3000"
    #environment:
    #- DISPLAY=host.docker.internal:0

networks:
  my_network:
    driver: bridge
