version: "3"

services:
  transmitter:
    container_name: transmitter
    build:
      context: ./sub
      dockerfile: Dockerfile
    image: amra-sub-transmitter-image
    volumes:
      - ./sub:/root/workspace
    tty: true
    networks:
      - my_network
    ports:
      - "12300:12300"
    depends_on:
      - receiver

  receiver:
    container_name: receiver
    build:
      context: ./gs
      dockerfile: Dockerfile
    image: amra-gs-receiver-image
    volumes:
      - ./gs:/root/workspace
      #- /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    networks:
      - my_network
    ports:
      - "12301:12301" # metric
      - "12302:12302" # video
    #environment:
    #- DISPLAY=host.docker.internal:0

networks:
  my_network:
    driver: bridge
